import Config

# Configure your database.
#
# In development the database comes from `DATABASE_URL` when it's set — a Neon
# Postgres URL exported from `.envrc` (direnv), so the password never lives in the
# repo. Without it, fall back to a local Postgres. Tests always use the local DB
# configured in `config/test.exs` (they never read `DATABASE_URL`).
if database_url = System.get_env("DATABASE_URL") do
  config :music_studio, MusicStudio.Repo,
    # Drop any libpq query params (e.g. ?sslmode=require&channel_binding=require);
    # SSL is configured explicitly below and channel binding is negotiated by Postgrex.
    url: database_url |> String.split("?") |> hd(),
    ssl: [verify: :verify_none],
    # Neon's pooled endpoint runs PgBouncer in transaction mode, which is incompatible
    # with named prepared statements — use unnamed ones to avoid "prepared statement
    # already exists" errors.
    prepare: :unnamed,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")
else
  config :music_studio, MusicStudio.Repo,
    username: "postgres",
    password: "postgres",
    hostname: "localhost",
    database: "music_studio_dev",
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :music_studio, MusicStudioWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "BE3EedVwPTXtKtNVHPcKYWRghdfDqBOm7j9ZcnuHQTXDc+pSk3cW5qa1ekFuqdHF",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:music_studio, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:music_studio, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :music_studio, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Import development secrets if they exist. See config/dev.secret.example.exs
# for the expected shape. Copy it to config/dev.secret.exs and fill in values.
if File.exists?("config/dev.secret.exs") do
  import_config "dev.secret.exs"
end
