import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :music_studio, MusicStudioWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :music_studio, MusicStudioWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Beacon compiles CMS page JS/CSS at RUNTIME via esbuild + tailwind (Beacon.RuntimeJS /
# BeaconRuntimeCSS), so those binaries must exist in the release image. Pin them to a
# fixed absolute path: by default the esbuild/tailwind packages derive the path from
# Mix.Project.build_path(), which is unavailable in a release and makes Beacon raise
# "esbuild binary not found" at boot. The Dockerfile installs the binaries here at build
# time and copies them into the runner stage at the same path.
config :esbuild, path: "/app/bin/esbuild"
config :tailwind, path: "/app/bin/tailwind"

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
